printWidth = 120      # 每行最大 80 字符
tabWidth = 2          # 缩进 2 空格
useTabs = false       # 用空格而非 Tab
semi = true           # 强制分号（避免歧义）
singleQuote = false   # 用双引号（JSON/TS 更一致）
trailingComma = "es5" # ES5兼容的尾随逗号
bracketSpacing = true # 对象 { key: value } 加空格
arrowParens = "avoid" # 箭头函数参数总是加括号：(x) => x
proseWrap = "always"  # Markdown 自动换行
endOfLine = "lf"      # 强制 Unix 换行符（避免 CRLF 问题）

plugins = ["prettier-plugin-tailwindcss"]
